# Linear Algebra
- You will be more incline to learn more mathematics once you have gotten your hands dirty applying machine learning to real datasets.

In [1]:
import torch

## 1. Scalars
- Scalars are variables. The yare implemented as tensors that contain only 1 elements.
- We assign 2 scalars and perform the familiar addition, multiplication, division, and expotentiation operations.

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2. Vectors
- Vector are fixed-legnth array of scalars. Thus, scalars can be the elements of the vectors.
- Vectos are implemented as first order tensors.

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
# Get the dimension
len(x)

3

## 3. Matrices
- Matrices are second-order tensors

In [6]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [7]:
# If we want to flip the axes, we can do transpose
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
# Same square matrices has equal to the transpose
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 4. Tensors
- Tensors allows us to describe n-th order arrays.
- Tensors are important when we work with images. Third order tensors has the axes (height, width, channel)

In [9]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 5. Basic Properties of Tensor Arithmetic

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [11]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [12]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 6. Reduction

In [13]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [14]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [15]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [16]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [17]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [18]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

## 7. Non-Reduction Sum

In [19]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [20]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [21]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## 8. Dot Products

In [22]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [23]:
torch.sum(x * y)

tensor(3.)

## 9. Matrix-Vector Product

In [24]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## 10. Matrix Multiplication

In [25]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

## 11. Norms
- The norm of the vector tells us how big it is.
- L1 Norm = Manhattan distance.
- L2 Norm = Euclidean distance.

In [26]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [27]:
torch.abs(u).sum()

tensor(7.)

In [28]:
# Frobenius norm
torch.norm(torch.ones((4, 9)))

tensor(6.)